openapi: 3.0.1
info:
  contact: {}
  description: Методы для работы с API codegen
  title: codegen API
  version: "1.0"
servers:
  - url: /
paths:
  /v1/specs/:
    get:
      description: Генерация спецификации сервера http
      operationId: GenerateSpecServerHttp
      parameters:
        - name: name
          description: Наименование сервера спецификации
          in: query
          schema:
            type: string
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateSpecServerHttpResponse200"
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateSpecServerHttpResponse500"
          description: Internal Server Error
    post:
      description: Выгрузка спецификации сервера http
      operationId: UploadSpecHttp
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadSpecHttpRequest"
        description: Параметры запроса
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadSpecHttpResponse200"
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadSpecHttpResponse500"
          description: Internal Server Error
      security:
        - bearer: []
components:
  schemas:
    ResponseStatusOk:
      type: object
      properties:
        code:
          type: string
          enum:
            - ok
        description:
          type: string
      required:
        - code
        - description
    ResponseStatusError:
      type: object
      properties:
        code:
          type: string
          enum:
            - error
        description:
          type: string
      required:
        - code
        - description
    UploadSpecHttpResponse200:
      type: object
      properties:
        status:
          type: object
          $ref: "#/components/schemas/ResponseStatusOk"
      required:
        - status
    UploadSpecHttpResponse500:
      type: object
      properties:
        status:
          type: object
          $ref: "#/components/schemas/ResponseStatusError"
      required:
        - status
    UploadSpecHttpRequest:
      type: object
      properties:
        name:
          type: string
          description: Название приложения спецификация которого выгружается
        spec:
          type: string
          format: byte
          description: Содержимое спецификации
      required:
        - name
        - spec
    GenerateSpecServerHttpResponse200:
      type: object
      properties:
        status:
          type: object
          $ref: "#/components/schemas/ResponseStatusOk"
        spec:
          type: string
          format: byte
          description: Содержимое спецификации
      required:
        - status
        - spec
    GenerateSpecServerHttpResponse500:
      type: object
      properties:
        status:
          type: object
          $ref: "#/components/schemas/ResponseStatusError"
      required:
        - status
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
